### ISSUE TITLE
Is it necessary to release resources?

### ISSUE THREAD

**Issue by rebeccalee97y** [corecode/dma#108]
Hi, there exists a obvious memory leak in dma.c.  See the following code, the allocated resource of _calloc_ is not freed when _strdup_ conducts error handling.
https://github.com/corecode/dma/blob/1b10f760900c57b14f98cc5e89a2ba4f7d063563/dma.c#L184-L189

Moreover, I have noticed one possible memory leak in the following code. At line 218, when _aliased < 0_ , the allocated resource by function _calloc_ and _strdup_ should be freed, with adding _free(it->addr);  free(it);_? 
https://github.com/corecode/dma/blob/1b10f760900c57b14f98cc5e89a2ba4f7d063563/dma.c#L215-L240

**Comment by corecode** [comment]
Hi,  thanks for the code review.

The intent is that memory allocation failure is critical and we cannot recover from it.  The code returns -1, which should signal to the caller a critical error, which should lead to exiting the process.  Because we know we will exit immediately, there is no need to complicate code by free()ing structures.

If there is any code path where an error result does not lead to the process exiting, then we need to make sure that the allocations do not accumulate.

**Comment by rebeccalee97y** [comment]
Thanks for the explanation :)
